### ISSUE TITLE
Fetching image field and uploading to cloudinary fails

### ISSUE THREAD

**Issue by SharadKumar** [fieldbook/api-docs#26]
Hi @jasoncrawford 
I have a use case where I use Fieldbook as backend UI and store. I pull content from a Book via API successfully (using axios) and sync into the website database. In my sheet I have an Image column. I need to upload the image from the sheet to Cloudinary.

As you'd see below, I pass `image.url` - url received in the sheet column - but it fails. I notice that when I paste the same url in browser, it goes through redirect with some kind of access attached to it. I am guessing this is to keep sheet content secure. How do I go about it? Any ideas will help.

```
Cloudinary.uploader.upload(image.url, Meteor.bindEnvironment(function(res) {
          if (!res.error) {
            Items.update({
              _id: foundItem._id
            }, {
              $push: {
                photos: res
              }
            });
            done({}, {
              success: true,
              message: image.name + ' uploaded successfully.'
            });
          } else {
            console.log(res.error);
            done({}, {
              success: false,
              message: image.name + ' failed to upload.'
            });
          }
        }));
      });
```

**Comment by jasoncrawford** [comment]
Yeah, if your sheet is not shared public read-only, then fetching the image requires login cookies.

You can set your book to be publicly viewable or publicly API-readable, which will make the images loadable without authentication.
