### ISSUE TITLE
Return All Books

### ISSUE THREAD

**Issue by jeffgipson** [fieldbook/api-docs#27]
Is it possible to send a request to /books and return a list of all books in an account?

**Comment by jasoncrawford** [comment]
Hi Jeff, can you describe what you might use this for exactly?

**Comment by jeffgipson** [comment]
Im adding Fieldbook to my API integration system. In my application (https://recruiterslogic.com) users are able to setup integrations via a simple UI. Instead of having users jump back and forth between apps we normally allow them to choose items like this from a drop down list. Feel free to check out my application.

**Comment by jasoncrawford** [comment]
Got it! So this is possible using Fieldbook OAuth, which is invite-only right now. Contact us through Fieldbook help chat or email us at support@fieldbook.com, and we can get you into this.
