### ISSUE TITLE
Feature request: Eager loading related rows

### ISSUE THREAD

**Issue by DeanWard** [fieldbook/api-docs#4]
When pulling in a sheet that has linked sheets it would be pretty nice to be able to pass a flag to include the full data for the relations instead of just an ID. To get around this currently I have to pull down the "main" sheet and then loop over all items, calling the API for each relation ID.

**Comment by jasoncrawford** [comment]
Thanks, good idea. What we've been thinking is that this would be included by default when you pull a single record, but not when you pull a list of records. Do you want full data for linked records when you pull a whole sheet? That would probably be done with a flag.

**Comment by DeanWard** [comment]
Yeah it would be nice to just be able to get "everything" in one shot, certainly would need to be behind a flag.

**Comment by thiagoperes** [comment]
+1 for that

**Comment by jasoncrawford** [comment]
Thanks guys. We are planning to add this via an `expand` parameter.

**Comment by nathanwaters** [comment]
+1 bump... @jasoncrawford is the expand parameter live?

**Comment by jasoncrawford** [comment]
Not yet, sorry! Will let you know.

**Comment by robertcarp** [comment]
To develop this idea a little further it would be great to have a checkbox field you could use to   select certain records in the ‘parent’ sheet, then create a JSON string which has the selected records in the parent sheet and the linked records in the ‘child’ sheets.

This JSON string could then be   copied into a different book but which has the same , configuration of sheets, fields, and formulas.   In this way institutions such as banks could completely transfer such things as data in a mortgage to  another bank which has purchased that mortgage.

I’ve started a little Fieldbook Codelet   to  get the ball rolling.  It works with Fieldbooks example database ‘sales pipeline’ with the addition of an ‘include’ checkbox column.   So far can pull in all meetings records for the selected companies and   return as JSON string.


const _ = require("underscore"); 

exports.endpoint = function (request, response, done) {  
    
     return client.list('meetings' ).then(function (plans)  {  
                
        return client.list('companies' ).then(function (dudes) {                                 
                                  
                 var keepers =  _.where(dudes, {include: true }) ;       
      
                 _.each (keepers, function(element, index, list) {
                 var meetups = [];
                 _.each (element.meetings, function(meetID, indxx, meets){
                 meetups.push(plans[meetID.id -1]) ;            
            
          } )          
            
           element.meetings =   meetups;          
          
  });    
           return( keepers);
     
     
  })
  
  });
  }

// Example of strategy for extracting records from child sheet with indexes found in parent:
// var A = [1,2,45,56,8.9,34,664,342];
// var B = [2,3,5]
// var C= [];
//  _.each(B, function (element, index, list) {
//     C.push(A[B[index]]);
// });
// C;

**Comment by allthesignals** [comment]
Does this work a single record yet?

**Comment by allthesignals** [comment]
```

**Comment by allthesignals** [comment]
```

**Comment by allthesignals** [comment]
(edit: sorry I keep hitting the wrong key and double posting) cleaning up formatting of @robertcarp's post, this could be used in an a codelet I'm guessing
```javascript
const _ = require("underscore");

exports.endpoint = function (request, response, done) {

  return client.list('meetings' ).then(function (plans)  {

    return client.list('companies' ).then(function (dudes) {                        

     var keepers =  _.where(dudes, {include: true });

      _.each (keepers, function(element, index, list) {
          var meetups = [];
          _.each (element.meetings, function(meetID, indxx, meets) {
            meetups.push(plans[meetID.id -1]);
          });
              
        element.meetings = meetups;          
      });

      return( keepers);
    });
  });
}

// Example of strategy for extracting records from child sheet with indexes found in parent:
// var A = [1,2,45,56,8.9,34,664,342];
// var B = [2,3,5]
// var C= [];
// _.each(B, function (element, index, list) {
// C.push(A[B[index]]);
// });
// C;
```

**Comment by allthesignals** [comment]
I found that in the "link settings" of a link field, if you update it to include the fields you want: 
![image](https://user-images.githubusercontent.com/5004319/31016163-a5a5ee78-a4f1-11e7-8dba-d269fe7b608e.png)
The API seems to eager load the linked records:
```json
{
  "count": 716,
  "offset": 5,
  "items": [
    {
      "id": 6,
      "type": "Retail",
      "activating_tl": [
        {
          "id": 369,
          "date": "5/1/2013",
          "value": "false"
        }
      ]
    },
```

**Comment by robertcarp** [comment]
Oh ok.  So in that way you can get all the fields in   first children records.  What would be nice is if you could do that for the linked  'grandchildren' records as well because   with Fieldbook you can  set up  a tree like data structure with    branches going down as far as you like.   What would be great is to have  a way to create a JSON text file corresponding to  selected records in the root sheet, all the records from any linked child sheets,  those child sheets   children's records, and so on.

**Comment by allthesignals** [comment]
@robertcarp What happens when you set link options to include grandchildren?

**Comment by robertcarp** [comment]
Well thats just it.  I'm not sure you can do that yet.  I think its something planned however.

**Comment by jasoncrawford** [comment]
@allthesignals @robertcarp Thanks guys… this will work but it's not really recommended, since what you're doing there is changing the display name of a record.

Let me see if we can get an `expand` parameter in the API for you soon.

**Comment by robertcarp** [comment]
@jasoncrawford 
Thanks Jason.

**Comment by jasoncrawford** [comment]
The `expand` parameter is now live! See updated docs and enjoy.
